### ISSUE TITLE
Background of reassigned contact: green until answered or closed, white when answered, grey when the contact wirtes back. - Software Needed / Updated

### ISSUE THREAD

**Issue by shahidykhan** [gmo/common#21]
Requester: Marian Douce
Requested Completion Date: 8/5/2022

When contact is reassigned, their background is now green and I don't have to accept it - that is great! After I write to or close that contact, the background should turn white (like other contacts I have answered). When the reassigned contact writes me back, their background should be grey - as it normally is to tell me that there is a new message form the contact. Right now, the background always stays green - I can't tell if they are newly reassigned, have written to me, or if I have answered them.

[https://app.zenhub.com/files/55992208/cf137c22-8a6b-4b8d-9f7d-e61b66101a78/download](https://app.zenhub.com/files/55992208/cf137c22-8a6b-4b8d-9f7d-e61b66101a78/download)

**Comment by mikegillis677** [comment]
@shahidykhan this ticket is in the wrong repo. Please delete and re-add in the path repo.

Also, please follow up and confirm with Michelle that this is the desired functionality.  Marian is not authorized to define requirements for new functionality, only to report bugs.

**Comment by celant12** [comment]
This is from Michelle:
When contact is reassigned, their background is now green and I don’t have to accept it - that is great! After I write to or close that contact, the background should turn white (like other contacts I have answered). When the reassigned contact writes me back, their background should be grey - as it normally is to tell me that there is a new message form the contact. Right now, the background always stays green - I can’t tell if they
