### ISSUE TITLE
SPIKE: Investigate and Write UP CI/CD Process Improvements

### ISSUE THREAD

**Issue by brianmckenzie** [gmo/common#30]

**Comment by brianmckenzie** [comment]
Investigate the capabilities of CircleCI and different CI/CD strategies we might use.
Consider the constraints in process the team is under i.e. the QA cycle.
Consider improvements in process that could greatly simplify this effort i.e. pull requests.
Consider any additional infrastructure we might need.
Write up conclusions for presentation to the team.

**Comment by mikegillis677** [comment]
wrong repo
