### ISSUE TITLE
CI / CD Pipeline Changes

### ISSUE THREAD

**Issue by nneuberger** [gmo/common#31]
This ticket will be an epic for all CI/CD pipeline changes.

**Comment by mikegillis677** [comment]
@nneuberger Please close this and make a new ticket in the gmo/path repo

**Comment by nneuberger** [comment]
wrong project closing ticket.

**Comment by nneuberger** [comment]
Dang good call. I created an Epic on that side

Nick

From: mikegillis677 ***@***.***>
Date: Wednesday, July 5, 2023 at 3:30 PM
To: gmo/common ***@***.***>
Cc: Nick Neuberger ***@***.***>, Mention ***@***.***>
Subject: Re: [gmo/common] CI / CD Pipeline Changes (Issue #31)

@nneuberger<https://github.com/nneuberger> Please close this and make a new ticket in the gmo/path repo
